### ISSUE TITLE
image_downloader_web >=2.0.0 depends on http ^0.13.5

### ISSUE THREAD

**Issue by alexVinarskis** [hrvojecukman/image_downloader_web#8]
Seems project depends on a _very_ old pinned version of `http`. Could you please update it?
In projects which use up-to-date `http` package, attempt to install `image_downloader_web` results in:
```
Because image_downloader_web >=2.0.0 depends on http ^0.13.5 and XXX depends on http ^1.1.0, image_downloader_web >=2.0.0 is forbidden.
So, because XXX depends on image_downloader_web ^2.0.2, version solving failed.
```

**Comment by wyyadd** [comment]
I sent a pr: https://github.com/hrvojecukman/image_downloader_web/pull/9

**Comment by hrvojecukman** [comment]
Thanks for the PR!
